Repository start-again/spookyBot, pull requests merged in 2020-10, with the labels that each got.

#27 Add local testing to readme
  README.md
  db/servers.json
Labels: documentation

#18 Add multiple Spanish words for the emojis
  lang/es.js
Labels: enhancement, translation

#38 Add hindi support
  lang/hi.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, translation

#44 Added Portuguese translation
  lang/pt.js
Labels: hacktoberfest-accepted, translation

#41 changed spooky bot to DM user instead of respond in channel
  commands/Sound/playsound.js
Labels: extension, hacktoberfest, hacktoberfest-accepted

#49 Added swedish translation
  lang/sv.js
Labels: translation

#32 Feature/more emojis
  lang/en.js
Labels: hacktoberfest-accepted

#45 Add trick or treat command
  commands/Text/trickortreat.js
  db/trickortreats.json
  handlers/command.js
  models/trickortreats.js
Labels: enhancement, hacktoberfest

#43 Custom trigger words for mentions
  lang/en.js
  utils/reactMessage.js
Labels: enhancement, hacktoberfest

#55 Added Chinese, Arabic, and Turkish
  lang/ar.js
  lang/tr.js
  lang/zh.js
Labels: hacktoberfest-accepted

#57 Update French language
  app/lang/fr.js
Labels: hacktoberfest, translation
